# Generated by Django 4.2.3 on 2023-07-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cord_x', models.CharField(max_length=30)),
                ('cord_y', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
    ]
