# Generated by Django 4.2.3 on 2023-07-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_marker_alter_maps_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
