# Generated by Django 4.2.3 on 2023-07-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_marker_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='marker_photos/'),
        ),
    ]
