# Generated by Django 4.2.3 on 2023-07-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_marker_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='description',
        ),
    ]
