# Generated by Django 4.2.3 on 2023-08-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_marker_aftephoto_marker_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='aftephoto',
            field=models.ImageField(blank=True, null=True, upload_to='marker_photos/'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='discription',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
