# Generated by Django 4.2.3 on 2023-08-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_remove_marker_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='aftephoto',
            field=models.ImageField(null=True, upload_to='marker_photos/'),
        ),
        migrations.AddField(
            model_name='marker',
            name='discription',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
