# Generated by Django 4.2.6 on 2023-10-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('images', models.ImageField(blank=True, upload_to='images/')),
                ('images2', models.ImageField(blank=True, upload_to='images/')),
                ('images3', models.ImageField(blank=True, upload_to='images/')),
                ('images4', models.ImageField(blank=True, upload_to='images/')),
                ('images5', models.ImageField(blank=True, upload_to='images/')),
                ('images6', models.ImageField(blank=True, upload_to='images/')),
                ('discription', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
