# Generated by Django 4.2.6 on 2023-10-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='discription',
            field=models.CharField(blank=True, max_length=100000000),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=4000),
        ),
    ]
