# Generated by Django 4.2.6 on 2023-10-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_discription_alter_news_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='small_discription',
            field=models.TextField(blank=True, max_length=100000000),
        ),
        migrations.AlterField(
            model_name='news',
            name='discription',
            field=models.TextField(blank=True, help_text='Enter field documentation', max_length=100000000),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.TextField(max_length=4000),
        ),
    ]
