# Generated by Django 4.2.13 on 2024-06-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='marker_photos/')),
                ('aftephoto', models.ImageField(blank=True, null=True, upload_to='marker_photos/')),
                ('discription', models.CharField(blank=True, max_length=140, null=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Подсказка - это будет отображаться в списке новостей.', max_length=4000, verbose_name='Название')),
                ('small_discription', models.TextField(blank=True, help_text='Максимум 100 символов!      Используется для отображения неполного описания в списке новостей.', max_length=100, verbose_name='Маленькое описание')),
                ('discription', models.TextField(blank=True, help_text='Ограничений нет!', max_length=100000000, verbose_name='Описание')),
                ('images', models.ImageField(blank=True, help_text='Титульная фотография', upload_to='images/')),
                ('images2', models.ImageField(blank=True, upload_to='images/')),
                ('images3', models.ImageField(blank=True, upload_to='images/')),
                ('images4', models.ImageField(blank=True, upload_to='images/')),
                ('images5', models.ImageField(blank=True, upload_to='images/')),
                ('images6', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
            ],
        ),
    ]
