# Generated by Django 4.2.7 on 2023-12-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='marker_photos/')),
                ('aftephoto', models.ImageField(blank=True, null=True, upload_to='marker_photos/')),
                ('discription', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=4000)),
                ('images', models.ImageField(blank=True, upload_to='images/')),
                ('images2', models.ImageField(blank=True, upload_to='images/')),
                ('images3', models.ImageField(blank=True, upload_to='images/')),
                ('images4', models.ImageField(blank=True, upload_to='images/')),
                ('images5', models.ImageField(blank=True, upload_to='images/')),
                ('images6', models.ImageField(blank=True, upload_to='images/')),
                ('discription', models.TextField(blank=True, max_length=100000000)),
            ],
        ),
    ]
